version: '3.8'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sqli_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
  web:
    image: mlai-lab/sqli-hard:latest
    build: .
    restart: always
    ports:
      - "${HOST_PORT}:80"
    depends_on:
      - mysql
